"""add product owner

Revision ID: b2070b53d3bb
Revises: 70f5d67153c1
Create Date: 2026-07-15 11:35:34.053111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2070b53d3bb'
down_revision: Union[str, Sequence[str], None] = '70f5d67153c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'owner_id')
    # ### end Alembic commands ###
